<?php
/**
 * Magento
 * @category   Payment
 * @package    Pdt_bank10
 * @copyright  Copyright (c) 2015 10bank.ir
 * @see http://10bank.ir
 */
?>
<html>
<meta http-equiv="refresh" content="0; URL=<?php echo $this->getContinueShoppingUrl() ?>">
<body>
<div class="page-head">
    <h3><?php echo $this->__('خطایی رخ داد') ?></h3>
</div>
<p><?php echo $this->__('با عرض پوزش خطایی در روند خرید رخ داد <a href="%s">ادامه خرید</a>.', $this->getContinueShoppingUrl()) ?></p>
</body>
</html>